name = "wallpaper-cutter"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".svelte-kit/cloudflare"

[env.production]
name = "wallpaper-cutter"

[env.preview]
name = "wallpaper-cutter-staging"
